#!/bin/bash
if [ $# -ne 1 ]
then
  echo "$0 <esp32-cam_IP>" >&2
  exit 2
fi
IP=$1
shift 1

timeout_s=10

flags=()
flags+=(-vvv) # verbose
flags+=(--no-qt-error-dialogs) # do not show pop-up windows
flags+=(--loop) # restart stream on failure
flags+=(--network-caching=0 --file-caching=0 --rtsp-caching=0 --live-caching=0) # disable any caching
flags+=(--no-drop-late-frames --no-skip-frames) # never drop frames
flags+=(--rtsp-tcp) # TCP streaming
flags+=(--rtsp-timeout="${timeout_s}000" --rtsp-session-timeout="${timeout_s}000" --ipv4-timeout="${timeout_s}000")
flags+=("rtsp://$IP:8554/mjpeg/2") # stream address

exec vlc "${flags[@]}"
